name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typescript Check
        run: pnpm run ts-check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
